### ISSUE TITLE
怎么判断有没有库乐队，库乐队的App Store链接是多少啊

### ISSUE THREAD

**Issue by FizzXiaoyu** [tangtiancheng/DouYinComment#11]

**Comment by tangtiancheng** [comment]
判断是否安装库乐队:[[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:@"garageband://"]];
appstore链接:  [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"https://itunes.apple.com/cn/app/garageband/id408709785?mt=8"]];
老哥,你这自己去看下不就行了,这也得提issue,服了你了
