### ISSUE TITLE
ExtAudioFileOpenURL() 在使用沙盒目录下的文件时会闪退

### ISSUE THREAD

**Issue by GenesisL** [tangtiancheng/DouYinComment#12]
感谢Demo，在使用过程中发现了几个问题想请教一下。
1. 在转换aiff文件的时候，使用包里的资源时没有问题，但是使用下载到沙盒的文件时ExtAudioFileOpenURL()会闪退，想问下有没有什么解决办法？
2. 导出库乐队文件时，只有aiff一种格式可以选择吗？还是说可以修改目录下的plist文件更换不同类型的资源？

**Comment by tangtiancheng** [comment]
1.你传的时候把文件后缀( .aac)去掉,比如传入("爱拼才会赢.aac" 改为 "爱拼才会赢" ), 你看一下是不是这个原因
2.这个我确实没试过,你可以试一下,本质相当于偷替换了苹果的库乐队支持的band文件中的内容,我感觉可能可以,你可以试一下,现在太晚了,我等有时间我自己再试一下,你也可以把你的结果和我说下

**Comment by tangtiancheng** [comment]
ole
