### ISSUE TITLE
请问下  机型是iPhone8 手机系统是iOS10.3.3 播放只有声音没有画面是咋回事

### ISSUE THREAD

**Issue by huxiaoxin** [tangtiancheng/DouYinComment#14]
// 增加下面这行可以解决iOS10兼容性问题了
    if ([self.player respondsToSelector:@selector(automaticallyWaitsToMinimizeStalling)]) {
        if (@available(iOS 10.0, *)) {
            self.player.automaticallyWaitsToMinimizeStalling = NO;
        } else {
            
            // Fallback on earlier versions
        }
    }
我看这段代码也执行了 没效果哎

不正常播放视频的地址：
http://1251606748.vod2.myqcloud.com/0767df4avodcq1251606748/dcf89a3d8602268011233048288/MYSIMlfhj44A.mp4

http://1251606748.vod2.myqcloud.com/0767df4avodcq1251606748/904489bc8602268011232084189/K8xAwAMHR6QA.mp4

http://1251606748.vod2.myqcloud.com/0767df4avodcq1251606748/2168249b8602268011237771450/LAClXX8pjNkA.mp4

http://1251606748.vod2.myqcloud.com/0767df4avodcq1251606748/08b3b49e8602268011230849229/vKrQTugjwtAA.mp4

正常播放视频的地址:
http://1251606748.vod2.myqcloud.com/0767df4avodcq1251606748/1c5da01d8602268011095274434/lskKcGN5IU0A.mp4

http://1251606748.vod2.myqcloud.com/0767df4avodcq1251606748/1c26ceda8602268011095243561/XrXJSAr120YA.mp4

**Comment by tangtiancheng** [comment]
兄弟,你自己在电脑上点开那4个不正常播放视频的地址看看,他本来就没视频呀,然后下面2个是有视频的.  本来就是有问题的

**Comment by tangtiancheng** [comment]
我看了一下,知道原因了,苹果是iOS11以后才支持H265视频编码的,最上面那4个视频都是H265编码,所以在iOS10上面无法解码,最下面两个是H264编码的,所以在iOS10及iOS10以后的版本都能显示视频. 这个你用其它第三方播放器应该也是只有声音没有视频,因为iOS10系统他就不支持H265
