### ISSUE TITLE
延续滑动的效果没有出来，是什么原因

### ISSUE THREAD

**Issue by kahoCHOY** [tangtiancheng/DouYinComment#19]
在真机上运行，延续滑动的效果没有

**Comment by tangtiancheng** [comment]
哎呀,我后面感觉添加滚动延续,代码更改复杂了很多,然后很多人没这个需求.怕新手不好看懂就删掉了这个功能.
https://github.com/tangtiancheng/DouYinComment/archive/refs/tags/0.0.7.zip  你可以下载我之前的这个版本,这里有滚动延续功能
