### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yangfangxue** [tangtiancheng/DouYinComment#20]
#pragma mark - SmallVideoPlayCellDlegate

//评论
- (void)handleCommentVidieoModel:(SmallVideoModel *)smallVideoModel {
    CommentsPopView *popView = [[CommentsPopView alloc] initWithSmallVideoModel:smallVideoModel];
    [popView showToView:self.view];
    [self.tableView reloadData];
}
如果点击评论添加一个reloadData的话 那么下拉的后面几个视频就会不动

**Comment by yangfangxue** [comment]
可能是因为刷新的时候FatherView的原因

**Comment by yangfangxue** [comment]
//因为播放器和进度条是加在cell.fatherView上的 刷新的时候由于重用机制导致了cell.fatherView的子视图不见了 
可以去掉cell的重用机制 如以下代码 
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    NSString *cellMark = [NSString stringWithFormat:@"SmallVideoPlayCell%ld", indexPath.row];
    SmallVideoPlayCell *cell = [tableView dequeueReusableCellWithIdentifier:cellMark];
    if(!cell){
        cell = [[SmallVideoPlayCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:cellMark];
    }
    cell.delegate = self;
    cell.model = self.datas[indexPath.row];
    return cell;
}

MARK:经过网上的搜索，采用最新版的ZFPlayer可以更好的做到视频向抖音那样上滑下滑，详情可见ZFPlayer Demo

**Comment by tangtiancheng** [comment]
嗯是的,这个仅做普通参考,一般加载更多用insert就行了,重用机制还是不要去掉比较好吧
