### ISSUE TITLE
使用bug

### ISSUE THREAD

**Issue by QJG010** [tangtiancheng/DouYinComment#5]
作者你好。使用时发现，如果childVC上有tableView嵌套collectionView的情况时，NestScrollPageViewHeadViewNoSuckTopType就会有问题。具体表现为：手指滑动位置在collectionView上时，就算没有滑动到最顶部，也会触发headView的放大效果

**Comment by tangtiancheng** [comment]
已经修复好啦

**Comment by QJG010** [comment]
谢谢大神提供支持。非常感谢！

发自我的iPhone
