### ISSUE TITLE
嵌套滑动问题

### ISSUE THREAD

**Issue by jasperchou** [tangtiancheng/DouYinComment#7]
滑动还是有缺陷。
在头部滑动的时候，不能连续滚动。
不知道有没有什么思路解决一下？

**Comment by tangtiancheng** [comment]
你的意思是手指拖拽头部,然后猛地向上一拉,然后想让下方的对应index的tableView也一起滚动吗?

**Comment by jasperchou** [comment]
是的啊哈哈。有什么想法？
我找了很多demo。这种方案实现的方法，只能是模拟手势后续滚动。
估计也没有更好的解决方法，所以只能否掉这种解决方案，干脆关了issue。

**Comment by tangtiancheng** [comment]
兄弟,你说的那个问题我已经解决了,思路感觉还挺取巧的,和网上那些几千star的都不一样,你可以下载最新的demo去看一下

**Comment by jasperchou** [comment]
> 兄弟,你说的那个问题我已经解决了,思路感觉还挺取巧的,和网上那些几千star的都不一样,你可以下载最新的demo去看一下
> @property (nonatomic, assign) BOOL scrolContinue;//是否支持header滚动延续  //(我自己写的滚动延续的原理和网上的不一样,我这边不要求改动你viewPage中各个控制器View的排版和层级, 做法是把要延续滚动的scrollView或者tableView或者collectionView的panGestureRecognizer取出来赋值给TCMainScrollView,这样你在拖拽header头部的时候也就相当于在拖拽下面的(scrollView或者tableView或者collectionView), 这样就能实现滚动延续了,而且尽可能的不侵入你的控制器代码)

虽然我已经用其他的框架解决了。并且，项目都已经不做了，但是作者还是给解决了哈哈哈。专门翻出来方案学习下，感谢！

**Comment by jasperchou** [comment]
点星加关注必须的了。
