### ISSUE TITLE
你好,想请教那个悬停框架

### ISSUE THREAD

**Issue by FaDeve** [tangtiancheng/DouYinComment#9]
就是现在有这么个场景,我用自己的viewpager,里面有个tableview列表,想点按钮的时候手动改变这个tableView的offset.现在发现只要一滑动列表,只有在悬停的时候,(mainTabelView不滑动的时候),这个修改才生效.可以怎么修改让不悬停的时候,我自己的tableview也可以响应滑动并改变offset,谢谢回复~

**Comment by tangtiancheng** [comment]
我写的这个不支持这样的效果,你看看网上有没其他类似的,但是我觉得够呛
